export const moviesData = [{
    id: 1,
    name: 'Interstellar',
    image: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/nCbkOyOMTEwlEV0LtCOvCnwEONA.jpg',
    isFavorited: true,
    description: 'Um grupo de exploradores viaja através de um buraco negro no espaço na tentativa de garantir a sobrevivência da humanidade.',
    releaseYear: 2014,
    director: 'Christopher Nolan',
  },
  {
    id: 2,
    name: 'Inception',
    image: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/k3UoZhRHg6h2XYzwNAJJvGC2yev.jpg',
    isFavorited: false,
    description: 'Um ladrão profissional é dado a chance de ter seu passado criminal apagado como pagamento por uma tarefa aparentemente impossível: implantar uma ideia na mente de uma pessoa.',
    releaseYear: 2010,
    director: 'Christopher Nolan',
  },
  {
    id: 3,
    name: 'The Matrix',
    image: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lDqMDI3xpbB9UQRyeXfei0MXhqb.jpg',
    isFavorited: false,
    description: 'Um programador de computador é levado a um mundo subterrâneo rebelde e começa a questionar a realidade.',
    releaseYear: 1999,
    director: 'Lana Wachowski, Lilly Wachowski',
  },
  {
    id: 4,
    name: 'Robocop',
    image: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fR0lfsB7YRNy2NQo9Ii7CPnYp31.jpg',
    isFavorited: false,
    description: 'Em um futuro distópico, um policial gravemente ferido retorna à força como um poderoso cyborg assombrado por memórias e sonhos sublimados.',
    releaseYear: 1987,
    director: 'Paul Verhoeven',
  },
  {
    id: 5,
    name: 'Terminator',
    image: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qvktm0BHcnmDpul4Hz01GIazWPr.jpg',
    isFavorited: false,
    description: 'Em um futuro pós-apocalíptico, um assassino cyborg é enviado de volta no tempo para eliminar uma garçonete, cujo filho futuro liderará a humanidade em uma guerra contra as máquinas.',
    releaseYear: 1984,
    director: 'James Cameron',
  },
  {
    id: 6,
    name: 'Starship Troopers',
    image: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/xb6NkoDkbep6lhn8K6YDPitALpr.jpg',
    isFavorited: false,
    description: 'Em um futuro fascista, os jovens são obrigados a se tornar cidadãos servindo ao estado militarizado, e a guerra contra os insetos alienígenas se torna uma forma de propaganda e recrutamento.',
    releaseYear: 1997,
    director: 'Paul Verhoeven',
  }];